name: 'ZIP TO S3'
description: 'Zip a NODE/NEXT project and publish a zip file to S3'
inputs:
  folder:  # folder name
    description: 'Folder Name'
    required: true
    default: 'production'
  aws_key_id:
    description: 'AWS Key ID'
    required: true
  aws_key:
    description: 'AWS Key'
    required: true
  aws_bucket:
    description: 'AWS Bucket'
    required: true
  files:
    description: 'Files to zip'
    required: true
    default: '.next/ next/ dist/ public/ node_modules/ package.json'
  addTests:
    description: 'Add tests?'
    required: true
    default: 'false'
  tests:
    description: 'Tests to zip'
    required: true
    default: 'tests/ test/ *test.* *config.*'
runs:
  using: 'composite'
  steps:
  - name: GET VERSION
    id: package-version
    uses: martinbeentjes/npm-get-version-action@main
  - name: 'Set Tests:'
    run: echo "TESTS=$(${{ inputs.addTests == 'true' }} && echo ${{ inputs.tests }} || echo '')" >> $GITHUB_ENV
    shell: bash
  - name: ZIP
    uses: vimtor/action-zip@master
    with:
      files: "${{ inputs.files }} ${{ env.TESTS }}"
      dest: ${{inputs.folder}}/${{ steps.package-version.outputs.current-version }}.zip
      recursive: false
  - name: Upload S3
    uses: shallwefootball/s3-upload-action@master
    id: S3
    with:
      aws_key_id: ${{ inputs.aws_key_id }}
      aws_secret_access_key: ${{ inputs.aws_key}}
      aws_bucket: ${{ inputs.aws_bucket }}
      source_dir: ${{inputs.folder}}
      destination_dir: ${{ github.event.repository.name }}/${{inputs.folder}}
